name: taskflow
description: TaskFlow helps you manage asynchronous tasks easily.
version: 0.1.1
homepage: https://github.com/ctrysbita/taskflow-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
